---
language: python
dist: focal
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  - pip install molecule[docker] docker ansible-lint flake8

script:
  - molecule test

# rename project directory to match Galaxy role name
before_script:
  - cd ../
  - mv ansible-role-grafana transitiv.grafana
  - cd transitiv.grafana

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
