---
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Ensure Grafana is started and enabled on boot
  service:
    name: grafana-server
    state: "{{ grafana_service_state }}"
    enabled: "{{ grafana_service_enabled }}"
