---
- name: Install Grafana repository key
  apt_key:
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
    url: https://packages.grafana.com/gpg.key
    keyring: /etc/apt/trusted.gpg.d/grafana.gpg
    state: present

- name: Install Grafana package repository
  apt_repository:
    repo: deb https://packages.grafana.com/{{ grafana_enterprise|bool|ternary('enterprise', 'oss') }}/deb {{ grafana_beta|bool|ternary('beta', 'stable') }} main
    state: present

- name: Install Grafana
  apt:
    name: "{{ grafana_enterprise|bool|ternary('grafana-enterprise', 'grafana') }}"
    state: present
    update_cache: yes
