---
- hosts: all
  tasks:
    - name: Install required packages on Debian
      apt:
        name:
          # required to add key to apt keyring
          - gnupg
          # required to verify grafana is running
          - procps
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install apt-transport-https on Debian 9
      apt:
        name:
          - apt-transport-https
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_release == 'stretch'
